name: Information

on: push

jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - run : |
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
  calculation:
    runs-on: windows-latest
    steps:
      - name: Calculate
        env:
          MAX_COUNT: 65535
        shell: cmd
        run: |
          set /a BUILD_NUMBER=%GITHUB_RUN_NUMBER%%%MAX_COUNT%
          echo BUILD_NUMBER=%BUILD_NUMBER% >> %GITHUB_ENV%
          echo REPOSITORY_NAME=%GITHUB_REPOSITORY:${{ github.repository_owner }}/=%>> %GITHUB_ENV%
      - name: Display
        shell: cmd
        run: |
          echo %BUILD_NUMBER%
          echo ^"%REPOSITORY_NAME%^"
          echo ^"%GITHUB_REPOSITORY%^"
