name: Release
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Show information for this action
        shell: cmd
        run: |
          cd
          dir
          echo ${{ GITHUB_WORKSPACE }}
          echo ${{ GITHUB_REPOSITORY }}
          echo ${{ GITHUB_EVENT_NAME }}
      
      - name: NUnit test with dotnet
        shell: cmd
        run: dotnet test
      
      - name: Build with dotnet
        shell: cmd
        run: dotnet msbuild ./MSBuildSampleForGitHubActions/MSBuildSampleForGitHubActions.csproj -t:build -restore -p:GenerateDocumentationFile=true;Configuration=Release;OutputPath=./Builds;AssemblyVersion=0.0.0.0;Version=0.0.0
