name: Release
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Show information for this action
        shell: cmd
        run: |
          cd
          dir
      
      - name: Build with MSBuild
        shell: cmd
        run: msbuild ./MSBuildSampleForGitHubActions/MSBuildSampleForGitHubActions.csproj -t:build -restore -p:GenerateDocumentationFile=true;Configuration=Release;OutputPath=./Builds;AssemblyVersion=0.0.0.0;Version=0.0.0
