name: Release

on:
  push:
    branches: 
      - main

jobs:
  information:
    runs-on: windows-2019
    env:
      HELLO_WORLD : "Hello world"
    steps:
      - name: Show information for this action
        run: |
          cd
          dir
          echo ${{ env.BUILD_FILE }}
          echo ${{ github.workspace }}
          echo %GITHUB_REPOSITORY%

  release:
    runs-on: windows-2019
    env:
      ENTRY_POINT_FILE: MSBuildSampleForGitHubActions/MSBuildSampleForGitHubActions.csproj
      BUILD_FILE: Builds
      ASSEMBLY_VERSION : 0.0.0.0
      PRODUCT_VERSION : 0.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Test
        shell: cmd
        run: dotnet test
      
      - name: Build
        shell: cmd
        run: |
          dotnet msbuild ${{ github.workspace }}/${{ env.ENTRY_POINT_FILE }} ^
          -t:build ^
          -restore ^
          -p:GenerateDocumentationFile=true^
          ;Configuration=Release^
          ;OutputPath=${{ github.workspace }}/${{ env.BUILD_FILE }}^
          ;AssemblyVersion=${{ env.ASSEMBLY_VERSION }}^
          ;Version=${{ env.PRODUCT_VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MSBuildSampleForGitHubActions
          path: ${{ github.workspace }}/${{ env.BUILD_FILE }}
