name: Validation for C#

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: windows-2019
    steps:
      - run : echo "test"
      # - name: Checkout
      #   uses: actions/checkout@v2
      
      # - name: Add MSBuild to Path
      #   uses: microsoft/setup-msbuild@v1.0.2
      
      # - name: Restore solution
      #   shell: cmd
      #   run: dotnet restore

      # - name: Test solution
      #   shell: cmd
      #   run: dotnet test
